apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: tpt-graph
  namespace: appsec
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "32Mi"
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  env:
    - name: WHODIS_URL
      value: http://whodis
    - name: OTEL_LOGS_EXPORTER
      value: otlp
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
  envFrom:
    - secret: tpt-graph
  ingresses:
    - https://tpt-graph.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "d633d27b-a470-4b9d-984e-85499f126e18"
          - id: "b0c13827-8451-4c52-9ed8-bdf09a2985a3"
          - id: "5f8b7bac-c3bf-4597-a9b1-42be0c8410f8"
          - id: "45e54224-3309-4797-89ed-a62aa76df3d0"
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: neo4j
        - application: whodis
