name: Automerge Dependabot PRs

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
    steps:
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@0e342d25820ca0d2941dcdcad4b7bbb59ad59122 # v1.5.1
        with:
          token: ${{ github.token }}
          merge-method: squash