name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: prod-gcp:appsec
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@1fae4798c79f4af4c3cdbd3fe65e51f8f3ba2368 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: appsec
          push_image: true
          pull: true
      - uses: nais/deploy/actions/deploy@961addd1e4d4211f1a7333ada5fde85f7c9aa5b7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
