name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: prod-gcp:appsec
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@f8bc7437f7549c2b08197152d781b98f8727a08a # v0
        id: docker-push
        with:
          team: appsec
      - uses: nais/deploy/actions/deploy@961addd1e4d4211f1a7333ada5fde85f7c9aa5b7 # ratchet:nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
